### ISSUE TITLE
Occasionally "PV Generation (All time)" goes out of whack

### ISSUE THREAD

**Issue by Sboshoff76** [celsworth/lxp-bridge#184]
![image](https://github.com/celsworth/lxp-bridge/assets/68126343/d9d74139-cd7e-4eab-a5ba-ed585fc8789a)

**Comment by celsworth** [comment]
Ah, floating point maths :) I assume this is the only key that does this? It will be because of this:

https://github.com/celsworth/lxp-bridge/blob/df38f1c51122fba212c2e9999277c94d7fb2adb7/src/lxp/packet.rs#L793

All of those are `f64`. `e_pv_day` will probably do the same thing occasionally.

I think this is mostly cosmetic to be fair, the rounding errors are pretty insignificant. I could work around it by doing maths in integer then converting back, will have a think.

**Comment by Sboshoff76** [comment]
Yeah wasnt a biggie, just thought I'd mention. Thanks for the fix!
