### ISSUE TITLE
AC Charge Switch seems to be 'read only'

### ISSUE THREAD

**Issue by JohnMacrae** [celsworth/lxp-bridge#219]
At some time in the last few weeks, the AC charge switch (and the discharge switch) seem to have become 'read only' in HA. What I mean by that is that they correctly reflect the state of the switch in the Lux app, but when activated, they switch on or off but then revert after a few seconds.  All other status information is correct. Can anyone point me in the right direction please?

**Comment by JohnMacrae** [comment]
It seems that, as usual, I found a solution immediately after posting the problem. I restarted the docker container (for the nth time) and this time is seems to have worked. Who knows for how long.

**Comment by celsworth** [comment]
Hm intriguing. Let us know if it happens again, could be good to get some logs to see what's going on. My best guess is lxp-bridge had lost it's subscription to MQTT (when you press that toggle in HA, it sends an MQTT message that lxp-bridge has to receive in order to action the request). So the first step would be "does that appear in the logs".
